"""add_gcs_support_to_contextfile

Revision ID: 2925d21b122e
Revises: 34649b4f19d7
Create Date: 2026-02-08 20:30:37.083057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2925d21b122e'
down_revision: Union[str, Sequence[str], None] = '34649b4f19d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contextfile', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('contextfile', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('contextfile', sa.Column('gcs_path', sa.String(length=500), nullable=False))
    op.add_column('contextfile', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('contextfile', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('contextfile', 'mine_type')
    op.drop_column('contextfile', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contextfile', sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contextfile', sa.Column('mine_type', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('contextfile', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('contextfile', 'created_at')
    op.drop_column('contextfile', 'gcs_path')
    op.drop_column('contextfile', 'file_size')
    op.drop_column('contextfile', 'mime_type')
    # ### end Alembic commands ###
