"""Añadiendo columna refresh_token_hash a tabla users

Revision ID: 41049d291f76
Revises: 92d85aebbe4c
Create Date: 2026-04-23 18:03:10.151794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41049d291f76'
down_revision: Union[str, Sequence[str], None] = '92d85aebbe4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###
