"""Añadiendo nueva columna a Tabla ContextFile, para aceptar hash de archivos y evitar duplicados

Revision ID: 59cd953fbdd5
Revises: cda13aea3ad6
Create Date: 2026-02-25 11:03:27.003130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cd953fbdd5'
down_revision: Union[str, Sequence[str], None] = 'cda13aea3ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contextfile', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_contextfile_file_hash'), 'contextfile', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contextfile_file_hash'), table_name='contextfile')
    op.drop_column('contextfile', 'file_hash')
    # ### end Alembic commands ###
