"""add microsoft provider fields

Revision ID: 92d85aebbe4c
Revises: 59cd953fbdd5
Create Date: 2026-03-25 21:29:45.560089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d85aebbe4c'
down_revision: Union[str, Sequence[str], None] = '59cd953fbdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1️⃣ Crear columna como nullable
    op.add_column(
        'oauth_connections',
        sa.Column('integration', sa.String(length=100), nullable=True)
    )

    # 2️⃣ Poblar datos existentes
    op.execute("""
        UPDATE oauth_connections
        SET integration = 'google:' || service
    """)

    # 3️⃣ Hacerla NOT NULL
    op.alter_column(
        'oauth_connections',
        'integration',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_connections', sa.Column('service', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('oauth_connections', 'integration')
    # ### end Alembic commands ###
