"""Modificando columnas en tabla Subscriptions

Revision ID: cda13aea3ad6
Revises: dff60236009b
Create Date: 2026-02-18 16:00:35.961868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda13aea3ad6'
down_revision: Union[str, Sequence[str], None] = 'dff60236009b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_customer_reference', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_transaction_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('subscriptions_stripe_customer_id_key'), 'subscriptions', type_='unique')
    op.drop_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'stripe_price_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('subscriptions_stripe_customer_id_key'), 'subscriptions', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscriptions', 'payment_transaction_id')
    op.drop_column('subscriptions', 'payment_customer_reference')
    # ### end Alembic commands ###
